homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_alt
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

camera:
  - platform: mjpeg
    name: office
    mjpeg_url: http://apa@192.168.10.101/video/mjpg.cgi
    still_image_url: http://apa@192.168.10.101/image/jpeg.cgi


zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 100
    icon: mdi:home

mqtt:
  broker: 192.168.10.44

device_tracker:
  - platform: nmap_tracker
    hosts:
     - 192.168.10.24
     - 192.168.10.45
    exclude:
     - 192.168.10.43
     - 192.168.10.44
    interval_seconds: 2000
    consider_home: 3600
    track_new_devices: true
  - platform: mqtt_json
    devices:
          sensasehlstedtse: 'location/klas'
          astrasehlstedtse: 'location/monika'
  #- platform: bluetooth_tracker
  #  interval_seconds: 10

  # - platform: ddwrt
  #   host: 192.168.10.249
  #   username: !secret ddwrt_user
  #   password: !secret ddwrt_password
  #   track_new_devices: true

proximity:
  home:
    devices:
      - device_tracker.sensasehlstedtse
      - device_tracker.astrasehlstedtse
    tolerance: 0
    #unit_of_measurement: km

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
  logger:
    title: Logger
    icon: mdi:printer
    url: http://hassio.local:4277
  router:
    title: 'Router'
    url: 'https://192.168.10.249'


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Vn
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
  - platform: yr
    name: Vp 24H
    forcast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
  - platform: yr
    name: Vp 48H
    forcast: 48
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
  - platform: command_line
    name: occasion
    command: "python3 /config/occasion.py"

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

python_script:

media_player:
  - platform: pioneer
    host: 192.168.10.41
    name: vsx923
    port: 8102
  # - platform: pioneer
  #   host: 192.168.10.46
  #   name: bdp450
  #   port: 8102
  # - platform: dlna_dmr
  #   name: ktm
  #   url: http://192.168.10.41

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#logger:
#  default: warning
#  logs:
#    homeassistant.components.mqtt: debug
