
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Customization file
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

tellduslive:
  host: 192.168.10.48
  scan_interval: 1

#panel_iframe:
#  ural:
#    title: 'ural'
#    url: 'https://192.168.10.252:10443'



# panel_iframe:
#  weather:
#    title: 'Hjälmared enligt windy.com'
#    url: 'https://embed.windy.com/embed2.html?lat=57.521&lon=12.151&detailLat=57.521&detailLon=12.151&width=650&height=450&zoom=11&level=surface&overlay=temp&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=m%2Fs&metricTemp=%C2%B0C&radarRange=-1'

switch:
  - platform: command_line
    #name: twinkly1
    switches:
      twinkly:
        command_on: "python3 /config/python_scripts/twinkly.py 192.168.10.47 on"
        command_off: "python3 /config/python_scripts/twinkly.py 192.168.10.47 off"
        command_state: "python3 /config/python_scripts/twinkly.py 192.168.10.47 state"
        value_template: "{{ value == \"1\" }}"
        friendly_name: Twinkly led slinga



python_script:

input_boolean: !include input_booleans.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
